dist: trusty
sudo: required

notifications:
    email: false

services:
  - docker

script:
    # Standard build
    - BUILD_ARGS="--no-cache" make build

after_success:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then TRAVIS_BRANCH=$TRAVIS_BRANCH DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD make push; fi'
